FROM python:3.9.20-bullseye

ARG DB_HOST

ENV DB_HOST=$DB_HOST
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Only copy backend directory contents
COPY backend/ .

# Install Python dependencies
RUN pip install --upgrade pip && \
    pip install django-environ && \
    pip install -r requirements.txt

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]