FROM python:3.9.20-bullseye

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY backend/ .

RUN pip install --upgrade pip && \
    pip install django-environ && \
    pip install -r requirements.txt

RUN python manage.py makemigrations account \
    python manage.py makemigrations payments \
    python manage.py makemigrations product

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]